properties


# Habilita el uso de las librerías de AndroidX
android.useAndroidX=true

# Convierte automáticamente librerías antiguas a AndroidX
android.enableJetifier=true

org.gradle.jvmargs=-Xmx1536m


MYAPP_RELEASE_STORE_FILE=/Users/benyistar/Downloads/ServicioTecnico/mi-app-clave.jks
MYAPP_RELEASE_STORE_PASSWORD=benyi123
MYAPP_RELEASE_KEY_ALIAS=mi-app-alias
MYAPP_RELEASE_KEY_PASSWORD=benyi123
